#!/usr/bin/env python3
"""Partition official LXGW WenKai v1.522 with the existing IMX font tooling.

Usage: python scripts/subset-wenkai.py Regular.ttf Medium.ttf
Install scripts/font-requirements.txt first. Outputs are relative to this repo.
"""
import importlib.util
from pathlib import Path
import sys

sys.dont_write_bytecode = True
spec = importlib.util.spec_from_file_location("imx_fonts", Path(__file__).with_name("subset-fonts.py"))
fonts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fonts)

SOURCES = {
    400: "39ad71264b588165b469e35e6afb162a378dacd1f95348160240ba9038ac3009",
    700: "d4bdeb38a39151d74d084cba5090f8cb7d20bf83eedb78c35939ae70b9f4e3f6",
}


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    if fonts.fontTools.__version__ != fonts.FONTTOOLS_VERSION:
        raise SystemExit("Install the pinned scripts/font-requirements.txt first")
    sources = dict(zip(SOURCES, map(Path, sys.argv[1:])))
    for weight, source in sources.items():
        if fonts.sha256(source) != SOURCES[weight]:
            raise SystemExit(f"Unexpected v1.522 source: {source}")

    root = Path(__file__).resolve().parent.parent
    css = ["/* Generated by scripts/subset-wenkai.py; LXGW WenKai v1.522. */"]
    manifest = []
    for weight, source in sources.items():
        with fonts.TTFont(source) as font:
            partitions = fonts.partition_codepoints(set(font.getBestCmap()))
        for partition, codepoints in partitions.items():
            relative = f"fonts/imx/wenkai-{weight}-{partition}.woff2"
            output = root / "assets" / relative
            fonts.subset_font(source, output, codepoints)
            manifest.append(f"{fonts.sha256(output)}  assets/{relative}")
            css.append(f'''@font-face {{
  font-family: 'IMX WenKai';
  src: url('{{{{ (resources.Get "{relative}" | fingerprint).RelPermalink }}}}') format('woff2');
  font-weight: {weight};
  font-style: normal;
  font-display: swap;
  unicode-range:
{fonts.format_unicode_range(codepoints)}
}}
''')
    (root / "assets/css/wenkai.css").write_text("\n".join(css))
    (root / "static/fonts/imx/wenkai-sha256.txt").write_text("\n".join(manifest) + "\n")


if __name__ == "__main__":
    main()
