#!/usr/bin/env python3
"""Build deterministic Noto Serif SC webfont partitions for IMX maintainers."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

import fontTools
from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont


FONTTOOLS_VERSION = "4.63.0"
EXPECTED_SOURCES = {
    "regular": "8126e6be407e8e0acc1a25604d7db7fea593c034cf41342fe624a13310c0f584",
    "bold": "82b4afbc537fe5579318dceeca654d815f70173183e20dd6d8ebc14701840027",
}
EXPECTED_OUTPUTS = {
    "noto-serif-sc-400-core.woff2": "d70c4c90898fc4745f1e5550a082d933fcb07bb3ac846ecb49ecd089abf51379",
    "noto-serif-sc-400-common.woff2": "ed936522eadb6a32b5df199196c968416dda2f153daa5b80ecd1c5d4ca746dd2",
    "noto-serif-sc-400-extended.woff2": "c07409ffc90fec98311b8dffd7bdc38121b06aa1bff3b317c1ba02d89f3af228",
    "noto-serif-sc-700-core.woff2": "48ebbcf99ff2b28c34926a57b31564da71c98f919daf3c5261528f7ca408e59d",
    "noto-serif-sc-700-common.woff2": "1e936c22005cb9318d5a002eebeafab5bf651f866dbca69404b302de084fc8c7",
    "noto-serif-sc-700-extended.woff2": "6a910bf112c062ae6bbecec50185601a34a333a4c81b7779063f66b0a654a048",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def gb2312_level(codepoint: int) -> str | None:
    try:
        encoded = chr(codepoint).encode("gb2312")
    except UnicodeEncodeError:
        return None

    if len(encoded) == 1 or encoded[0] < 0xB0:
        return "core"
    if 0xB0 <= encoded[0] <= 0xD7:
        return "core"
    if 0xD8 <= encoded[0] <= 0xF7:
        return "common"
    return None


def partition_codepoints(codepoints: set[int]) -> dict[str, set[int]]:
    partitions = {"core": set(), "common": set(), "extended": set()}
    core_ranges = (
        (0x0000, 0x02FF),
        (0x2000, 0x27BF),
        (0x2E80, 0x303F),
        (0x31C0, 0x31EF),
        (0xFE10, 0xFE6F),
        (0xFF00, 0xFFEF),
    )

    for codepoint in codepoints:
        level = gb2312_level(codepoint)
        if level:
            partitions[level].add(codepoint)
            continue
        if any(start <= codepoint <= end for start, end in core_ranges):
            partitions["core"].add(codepoint)
            continue
        partitions["extended"].add(codepoint)

    return partitions


def compact_ranges(codepoints: set[int]) -> list[str]:
    ordered = sorted(codepoints)
    ranges: list[tuple[int, int]] = []
    start = previous = ordered[0]

    for codepoint in ordered[1:]:
        if codepoint == previous + 1:
            previous = codepoint
            continue
        ranges.append((start, previous))
        start = previous = codepoint
    ranges.append((start, previous))

    return [
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in ranges
    ]


def format_unicode_range(codepoints: set[int]) -> str:
    ranges = compact_ranges(codepoints)
    lines = []
    for index in range(0, len(ranges), 8):
        suffix = "," if index + 8 < len(ranges) else ";"
        lines.append("    " + ", ".join(ranges[index:index + 8]) + suffix)
    return "\n".join(lines)


def subset_font(source_path: Path, output_path: Path, codepoints: set[int]) -> None:
    font = TTFont(source_path, recalcTimestamp=False)
    options = Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.name_legacy = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    subsetter = Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    font.flavor = "woff2"
    font.recalcTimestamp = False
    output_path.parent.mkdir(parents=True, exist_ok=True)
    font.save(output_path, reorderTables=None)


def font_face(weight: int, partition: str, codepoints: set[int]) -> str:
    resource_key = f"noto{weight}{partition.title()}"
    return f"""@font-face {{
  font-family: 'IMX Noto Serif SC';
  src: url('{{{{ .{resource_key}.RelPermalink }}}}') format('woff2');
  font-weight: {weight};
  font-style: normal;
  font-display: optional;
  unicode-range:
{format_unicode_range(codepoints)}
}}
"""


def build_css(partitions: dict[str, set[int]]) -> str:
    faces = [
        """/* Generated by scripts/subset-fonts.py with fontTools 4.63.0. */
@font-face {
  font-family: 'IMX Inter';
  src: url('{{ .inter.RelPermalink }}') format('woff2-variations');
  font-weight: 100 900;
  font-style: normal;
  font-display: optional;
}

@font-face {
  font-family: 'IMX Noto Serif SC Fallback';
  src: local('Noto Serif CJK SC'), local('Source Han Serif SC'),
       local('Songti SC'), local('STSong'), local('SimSun');
  font-weight: 400 700;
  font-style: normal;
  size-adjust: 100%;
  ascent-override: 115.1%;
  descent-override: 28.6%;
  line-gap-override: 0%;
}
"""
    ]
    for weight in (400, 700):
        for partition in ("extended", "common", "core"):
            faces.append(font_face(weight, partition, partitions[partition]))
    return "\n".join(faces)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--regular-source", required=True, type=Path)
    parser.add_argument("--bold-source", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--css-output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if fontTools.__version__ != FONTTOOLS_VERSION:
        raise SystemExit(
            f"fontTools {FONTTOOLS_VERSION} is required; found {fontTools.__version__}"
        )

    sources = {"regular": args.regular_source, "bold": args.bold_source}
    for style, source_path in sources.items():
        actual = sha256(source_path)
        if actual != EXPECTED_SOURCES[style]:
            raise SystemExit(
                f"Unexpected {style} source checksum: {actual}"
            )

    regular = TTFont(args.regular_source, recalcTimestamp=False)
    bold = TTFont(args.bold_source, recalcTimestamp=False)
    regular_codepoints = set(regular.getBestCmap())
    bold_codepoints = set(bold.getBestCmap())
    if regular_codepoints != bold_codepoints:
        raise SystemExit("Regular and bold fonts do not expose the same character map")

    partitions = partition_codepoints(regular_codepoints)
    if set().union(*partitions.values()) != regular_codepoints:
        raise SystemExit("Font partitions do not cover the complete character map")
    if sum(len(partition) for partition in partitions.values()) != len(regular_codepoints):
        raise SystemExit("Font partitions overlap")

    for style, weight in (("regular", 400), ("bold", 700)):
        for partition, codepoints in partitions.items():
            output_path = args.output_dir / f"noto-serif-sc-{weight}-{partition}.woff2"
            subset_font(sources[style], output_path, codepoints)

    for filename, expected in EXPECTED_OUTPUTS.items():
        actual = sha256(args.output_dir / filename)
        if actual != expected:
            raise SystemExit(f"Unexpected generated font checksum for {filename}: {actual}")

    args.css_output.parent.mkdir(parents=True, exist_ok=True)
    args.css_output.write_text(build_css(partitions), encoding="utf-8")

    for partition in ("core", "common", "extended"):
        print(f"{partition}: {len(partitions[partition])} codepoints")
    return 0


if __name__ == "__main__":
    sys.exit(main())
